// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MoneyMaker.Data;

#nullable disable

namespace MoneyMaker.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20220320225904_CurrencySampleData")]
    partial class CurrencySampleData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.3");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("RoleId")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("MoneyMaker.Models.Alert", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("FromCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("ToCurrency")
                        .HasColumnType("TEXT");

                    b.Property<string>("AlertName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<float>("ConditionValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("TEXT");

                    b.Property<bool>("isBelow")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "FromCurrency", "ToCurrency");

                    b.ToTable("Alert");
                });

            modelBuilder.Entity("MoneyMaker.Models.Currency", b =>
                {
                    b.Property<string>("CurrencySym")
                        .HasColumnType("TEXT");

                    b.Property<string>("CurrencyFullName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CurrencySym");

                    b.ToTable("Currencies");

                    b.HasData(
                        new
                        {
                            CurrencySym = "AED",
                            CurrencyFullName = "United Arab Emirates Dirham"
                        },
                        new
                        {
                            CurrencySym = "AFN",
                            CurrencyFullName = "Afghan Afghani"
                        },
                        new
                        {
                            CurrencySym = "ALL",
                            CurrencyFullName = "Albanian Lek"
                        },
                        new
                        {
                            CurrencySym = "AMD",
                            CurrencyFullName = "Armenian Dram"
                        },
                        new
                        {
                            CurrencySym = "ANG",
                            CurrencyFullName = "Netherlands Antillean Guilder"
                        },
                        new
                        {
                            CurrencySym = "AOA",
                            CurrencyFullName = "Angolan Kwanza"
                        },
                        new
                        {
                            CurrencySym = "ARS",
                            CurrencyFullName = "Argentine Peso"
                        },
                        new
                        {
                            CurrencySym = "AUD",
                            CurrencyFullName = "Australian Dollar"
                        },
                        new
                        {
                            CurrencySym = "AWG",
                            CurrencyFullName = "Aruban Florin"
                        },
                        new
                        {
                            CurrencySym = "AZN",
                            CurrencyFullName = "Azerbaijani Manat"
                        },
                        new
                        {
                            CurrencySym = "BAM",
                            CurrencyFullName = "Bosnia-Herzegovina Convertible Mark"
                        },
                        new
                        {
                            CurrencySym = "BBD",
                            CurrencyFullName = "Barbadian Dollar"
                        },
                        new
                        {
                            CurrencySym = "BDT",
                            CurrencyFullName = "Bangladeshi Taka"
                        },
                        new
                        {
                            CurrencySym = "BGN",
                            CurrencyFullName = "Bulgarian Lev"
                        },
                        new
                        {
                            CurrencySym = "BHD",
                            CurrencyFullName = "Bahraini Dinar"
                        },
                        new
                        {
                            CurrencySym = "BIF",
                            CurrencyFullName = "Burundian Franc"
                        },
                        new
                        {
                            CurrencySym = "BMD",
                            CurrencyFullName = "Bermudan Dollar"
                        },
                        new
                        {
                            CurrencySym = "BND",
                            CurrencyFullName = "Brunei Dollar"
                        },
                        new
                        {
                            CurrencySym = "BOB",
                            CurrencyFullName = "Bolivian Boliviano"
                        },
                        new
                        {
                            CurrencySym = "BRL",
                            CurrencyFullName = "Brazilian Real"
                        },
                        new
                        {
                            CurrencySym = "BSD",
                            CurrencyFullName = "Bahamian Dollar"
                        },
                        new
                        {
                            CurrencySym = "BTC",
                            CurrencyFullName = "Bitcoin"
                        },
                        new
                        {
                            CurrencySym = "BTN",
                            CurrencyFullName = "Bhutanese Ngultrum"
                        },
                        new
                        {
                            CurrencySym = "BWP",
                            CurrencyFullName = "Botswanan Pula"
                        },
                        new
                        {
                            CurrencySym = "BYN",
                            CurrencyFullName = "Belarusian Ruble"
                        },
                        new
                        {
                            CurrencySym = "BZD",
                            CurrencyFullName = "Belize Dollar"
                        },
                        new
                        {
                            CurrencySym = "CAD",
                            CurrencyFullName = "Canadian Dollar"
                        },
                        new
                        {
                            CurrencySym = "CDF",
                            CurrencyFullName = "Congolese Franc"
                        },
                        new
                        {
                            CurrencySym = "CHF",
                            CurrencyFullName = "Swiss Franc"
                        },
                        new
                        {
                            CurrencySym = "CLF",
                            CurrencyFullName = "Chilean Unit of Account (UF)"
                        },
                        new
                        {
                            CurrencySym = "CLP",
                            CurrencyFullName = "Chilean Peso"
                        },
                        new
                        {
                            CurrencySym = "CNH",
                            CurrencyFullName = "Chinese Yuan (Offshore)"
                        },
                        new
                        {
                            CurrencySym = "CNY",
                            CurrencyFullName = "Chinese Yuan"
                        },
                        new
                        {
                            CurrencySym = "COP",
                            CurrencyFullName = "Colombian Peso"
                        },
                        new
                        {
                            CurrencySym = "CRC",
                            CurrencyFullName = "Costa Rican Col�n"
                        },
                        new
                        {
                            CurrencySym = "CUC",
                            CurrencyFullName = "Cuban Convertible Peso"
                        },
                        new
                        {
                            CurrencySym = "CUP",
                            CurrencyFullName = "Cuban Peso"
                        },
                        new
                        {
                            CurrencySym = "CVE",
                            CurrencyFullName = "Cape Verdean Escudo"
                        },
                        new
                        {
                            CurrencySym = "CZK",
                            CurrencyFullName = "Czech Republic Koruna"
                        },
                        new
                        {
                            CurrencySym = "DJF",
                            CurrencyFullName = "Djiboutian Franc"
                        },
                        new
                        {
                            CurrencySym = "DKK",
                            CurrencyFullName = "Danish Krone"
                        },
                        new
                        {
                            CurrencySym = "DOP",
                            CurrencyFullName = "Dominican Peso"
                        },
                        new
                        {
                            CurrencySym = "DZD",
                            CurrencyFullName = "Algerian Dinar"
                        },
                        new
                        {
                            CurrencySym = "EGP",
                            CurrencyFullName = "Egyptian Pound"
                        },
                        new
                        {
                            CurrencySym = "ERN",
                            CurrencyFullName = "Eritrean Nakfa"
                        },
                        new
                        {
                            CurrencySym = "ETB",
                            CurrencyFullName = "Ethiopian Birr"
                        },
                        new
                        {
                            CurrencySym = "EUR",
                            CurrencyFullName = "Euro"
                        },
                        new
                        {
                            CurrencySym = "FJD",
                            CurrencyFullName = "Fijian Dollar"
                        },
                        new
                        {
                            CurrencySym = "FKP",
                            CurrencyFullName = "Falkland Islands Pound"
                        },
                        new
                        {
                            CurrencySym = "GBP",
                            CurrencyFullName = "British Pound Sterling"
                        },
                        new
                        {
                            CurrencySym = "GEL",
                            CurrencyFullName = "Georgian Lari"
                        },
                        new
                        {
                            CurrencySym = "GGP",
                            CurrencyFullName = "Guernsey Pound"
                        },
                        new
                        {
                            CurrencySym = "GHS",
                            CurrencyFullName = "Ghanaian Cedi"
                        },
                        new
                        {
                            CurrencySym = "GIP",
                            CurrencyFullName = "Gibraltar Pound"
                        },
                        new
                        {
                            CurrencySym = "GMD",
                            CurrencyFullName = "Gambian Dalasi"
                        },
                        new
                        {
                            CurrencySym = "GNF",
                            CurrencyFullName = "Guinean Franc"
                        },
                        new
                        {
                            CurrencySym = "GTQ",
                            CurrencyFullName = "Guatemalan Quetzal"
                        },
                        new
                        {
                            CurrencySym = "GYD",
                            CurrencyFullName = "Guyanaese Dollar"
                        },
                        new
                        {
                            CurrencySym = "HKD",
                            CurrencyFullName = "Hong Kong Dollar"
                        },
                        new
                        {
                            CurrencySym = "HNL",
                            CurrencyFullName = "Honduran Lempira"
                        },
                        new
                        {
                            CurrencySym = "HRK",
                            CurrencyFullName = "Croatian Kuna"
                        },
                        new
                        {
                            CurrencySym = "HTG",
                            CurrencyFullName = "Haitian Gourde"
                        },
                        new
                        {
                            CurrencySym = "HUF",
                            CurrencyFullName = "Hungarian Forint"
                        },
                        new
                        {
                            CurrencySym = "IDR",
                            CurrencyFullName = "Indonesian Rupiah"
                        },
                        new
                        {
                            CurrencySym = "ILS",
                            CurrencyFullName = "Israeli New Sheqel"
                        },
                        new
                        {
                            CurrencySym = "IMP",
                            CurrencyFullName = "Manx pound"
                        },
                        new
                        {
                            CurrencySym = "INR",
                            CurrencyFullName = "Indian Rupee"
                        },
                        new
                        {
                            CurrencySym = "IQD",
                            CurrencyFullName = "Iraqi Dinar"
                        },
                        new
                        {
                            CurrencySym = "IRR",
                            CurrencyFullName = "Iranian Rial"
                        },
                        new
                        {
                            CurrencySym = "ISK",
                            CurrencyFullName = "Icelandic Kr�na"
                        },
                        new
                        {
                            CurrencySym = "JEP",
                            CurrencyFullName = "Jersey Pound"
                        },
                        new
                        {
                            CurrencySym = "JMD",
                            CurrencyFullName = "Jamaican Dollar"
                        },
                        new
                        {
                            CurrencySym = "JOD",
                            CurrencyFullName = "Jordanian Dinar"
                        },
                        new
                        {
                            CurrencySym = "JPY",
                            CurrencyFullName = "Japanese Yen"
                        },
                        new
                        {
                            CurrencySym = "KES",
                            CurrencyFullName = "Kenyan Shilling"
                        },
                        new
                        {
                            CurrencySym = "KGS",
                            CurrencyFullName = "Kyrgystani Som"
                        },
                        new
                        {
                            CurrencySym = "KHR",
                            CurrencyFullName = "Cambodian Riel"
                        },
                        new
                        {
                            CurrencySym = "KMF",
                            CurrencyFullName = "Comorian Franc"
                        },
                        new
                        {
                            CurrencySym = "KPW",
                            CurrencyFullName = "North Korean Won"
                        },
                        new
                        {
                            CurrencySym = "KRW",
                            CurrencyFullName = "South Korean Won"
                        },
                        new
                        {
                            CurrencySym = "KWD",
                            CurrencyFullName = "Kuwaiti Dinar"
                        },
                        new
                        {
                            CurrencySym = "KYD",
                            CurrencyFullName = "Cayman Islands Dollar"
                        },
                        new
                        {
                            CurrencySym = "KZT",
                            CurrencyFullName = "Kazakhstani Tenge"
                        },
                        new
                        {
                            CurrencySym = "LAK",
                            CurrencyFullName = "Laotian Kip"
                        },
                        new
                        {
                            CurrencySym = "LBP",
                            CurrencyFullName = "Lebanese Pound"
                        },
                        new
                        {
                            CurrencySym = "LKR",
                            CurrencyFullName = "Sri Lankan Rupee"
                        },
                        new
                        {
                            CurrencySym = "LRD",
                            CurrencyFullName = "Liberian Dollar"
                        },
                        new
                        {
                            CurrencySym = "LSL",
                            CurrencyFullName = "Lesotho Loti"
                        },
                        new
                        {
                            CurrencySym = "LYD",
                            CurrencyFullName = "Libyan Dinar"
                        },
                        new
                        {
                            CurrencySym = "MAD",
                            CurrencyFullName = "Moroccan Dirham"
                        },
                        new
                        {
                            CurrencySym = "MDL",
                            CurrencyFullName = "Moldovan Leu"
                        },
                        new
                        {
                            CurrencySym = "MGA",
                            CurrencyFullName = "Malagasy Ariary"
                        },
                        new
                        {
                            CurrencySym = "MKD",
                            CurrencyFullName = "Macedonian Denar"
                        },
                        new
                        {
                            CurrencySym = "MMK",
                            CurrencyFullName = "Myanma Kyat"
                        },
                        new
                        {
                            CurrencySym = "MNT",
                            CurrencyFullName = "Mongolian Tugrik"
                        },
                        new
                        {
                            CurrencySym = "MOP",
                            CurrencyFullName = "Macanese Pataca"
                        },
                        new
                        {
                            CurrencySym = "MRO",
                            CurrencyFullName = "Mauritanian Ouguiya (pre-2018)"
                        },
                        new
                        {
                            CurrencySym = "MRU",
                            CurrencyFullName = "Mauritanian Ouguiya"
                        },
                        new
                        {
                            CurrencySym = "MUR",
                            CurrencyFullName = "Mauritian Rupee"
                        },
                        new
                        {
                            CurrencySym = "MVR",
                            CurrencyFullName = "Maldivian Rufiyaa"
                        },
                        new
                        {
                            CurrencySym = "MWK",
                            CurrencyFullName = "Malawian Kwacha"
                        },
                        new
                        {
                            CurrencySym = "MXN",
                            CurrencyFullName = "Mexican Peso"
                        },
                        new
                        {
                            CurrencySym = "MYR",
                            CurrencyFullName = "Malaysian Ringgit"
                        },
                        new
                        {
                            CurrencySym = "MZN",
                            CurrencyFullName = "Mozambican Metical"
                        },
                        new
                        {
                            CurrencySym = "NAD",
                            CurrencyFullName = "Namibian Dollar"
                        },
                        new
                        {
                            CurrencySym = "NGN",
                            CurrencyFullName = "Nigerian Naira"
                        },
                        new
                        {
                            CurrencySym = "NIO",
                            CurrencyFullName = "Nicaraguan C�rdoba"
                        },
                        new
                        {
                            CurrencySym = "NOK",
                            CurrencyFullName = "Norwegian Krone"
                        },
                        new
                        {
                            CurrencySym = "NPR",
                            CurrencyFullName = "Nepalese Rupee"
                        },
                        new
                        {
                            CurrencySym = "NZD",
                            CurrencyFullName = "New Zealand Dollar"
                        },
                        new
                        {
                            CurrencySym = "OMR",
                            CurrencyFullName = "Omani Rial"
                        },
                        new
                        {
                            CurrencySym = "PAB",
                            CurrencyFullName = "Panamanian Balboa"
                        },
                        new
                        {
                            CurrencySym = "PEN",
                            CurrencyFullName = "Peruvian Nuevo Sol"
                        },
                        new
                        {
                            CurrencySym = "PGK",
                            CurrencyFullName = "Papua New Guinean Kina"
                        },
                        new
                        {
                            CurrencySym = "PHP",
                            CurrencyFullName = "Philippine Peso"
                        },
                        new
                        {
                            CurrencySym = "PKR",
                            CurrencyFullName = "Pakistani Rupee"
                        },
                        new
                        {
                            CurrencySym = "PLN",
                            CurrencyFullName = "Polish Zloty"
                        },
                        new
                        {
                            CurrencySym = "PYG",
                            CurrencyFullName = "Paraguayan Guarani"
                        },
                        new
                        {
                            CurrencySym = "QAR",
                            CurrencyFullName = "Qatari Rial"
                        },
                        new
                        {
                            CurrencySym = "RON",
                            CurrencyFullName = "Romanian Leu"
                        },
                        new
                        {
                            CurrencySym = "RSD",
                            CurrencyFullName = "Serbian Dinar"
                        },
                        new
                        {
                            CurrencySym = "RUB",
                            CurrencyFullName = "Russian Ruble"
                        },
                        new
                        {
                            CurrencySym = "RWF",
                            CurrencyFullName = "Rwandan Franc"
                        },
                        new
                        {
                            CurrencySym = "SAR",
                            CurrencyFullName = "Saudi Riyal"
                        },
                        new
                        {
                            CurrencySym = "SBD",
                            CurrencyFullName = "Solomon Islands Dollar"
                        },
                        new
                        {
                            CurrencySym = "SCR",
                            CurrencyFullName = "Seychellois Rupee"
                        },
                        new
                        {
                            CurrencySym = "SDG",
                            CurrencyFullName = "Sudanese Pound"
                        },
                        new
                        {
                            CurrencySym = "SEK",
                            CurrencyFullName = "Swedish Krona"
                        },
                        new
                        {
                            CurrencySym = "SGD",
                            CurrencyFullName = "Singapore Dollar"
                        },
                        new
                        {
                            CurrencySym = "SHP",
                            CurrencyFullName = "Saint Helena Pound"
                        },
                        new
                        {
                            CurrencySym = "SLL",
                            CurrencyFullName = "Sierra Leonean Leone"
                        },
                        new
                        {
                            CurrencySym = "SOS",
                            CurrencyFullName = "Somali Shilling"
                        },
                        new
                        {
                            CurrencySym = "SRD",
                            CurrencyFullName = "Surinamese Dollar"
                        },
                        new
                        {
                            CurrencySym = "SSP",
                            CurrencyFullName = "South Sudanese Pound"
                        },
                        new
                        {
                            CurrencySym = "STD",
                            CurrencyFullName = "S�o Tom� and Pr�ncipe Dobra (pre-2018)"
                        },
                        new
                        {
                            CurrencySym = "STN",
                            CurrencyFullName = "S�o Tom� and Pr�ncipe Dobra"
                        },
                        new
                        {
                            CurrencySym = "SVC",
                            CurrencyFullName = "Salvadoran Col�n"
                        },
                        new
                        {
                            CurrencySym = "SYP",
                            CurrencyFullName = "Syrian Pound"
                        },
                        new
                        {
                            CurrencySym = "SZL",
                            CurrencyFullName = "Swazi Lilangeni"
                        },
                        new
                        {
                            CurrencySym = "THB",
                            CurrencyFullName = "Thai Baht"
                        },
                        new
                        {
                            CurrencySym = "TJS",
                            CurrencyFullName = "Tajikistani Somoni"
                        },
                        new
                        {
                            CurrencySym = "TMT",
                            CurrencyFullName = "Turkmenistani Manat"
                        },
                        new
                        {
                            CurrencySym = "TND",
                            CurrencyFullName = "Tunisian Dinar"
                        },
                        new
                        {
                            CurrencySym = "TOP",
                            CurrencyFullName = "Tongan Pa'anga"
                        },
                        new
                        {
                            CurrencySym = "TRY",
                            CurrencyFullName = "Turkish Lira"
                        },
                        new
                        {
                            CurrencySym = "TTD",
                            CurrencyFullName = "Trinidad and Tobago Dollar"
                        },
                        new
                        {
                            CurrencySym = "TWD",
                            CurrencyFullName = "New Taiwan Dollar"
                        },
                        new
                        {
                            CurrencySym = "TZS",
                            CurrencyFullName = "Tanzanian Shilling"
                        },
                        new
                        {
                            CurrencySym = "UAH",
                            CurrencyFullName = "Ukrainian Hryvnia"
                        },
                        new
                        {
                            CurrencySym = "UGX",
                            CurrencyFullName = "Ugandan Shilling"
                        },
                        new
                        {
                            CurrencySym = "USD",
                            CurrencyFullName = "United States Dollar"
                        },
                        new
                        {
                            CurrencySym = "UYU",
                            CurrencyFullName = "Uruguayan Peso"
                        },
                        new
                        {
                            CurrencySym = "UZS",
                            CurrencyFullName = "Uzbekistan Som"
                        },
                        new
                        {
                            CurrencySym = "VEF",
                            CurrencyFullName = "Venezuelan Bol�var Fuerte (Old)"
                        },
                        new
                        {
                            CurrencySym = "VES",
                            CurrencyFullName = "Venezuelan Bol�var Soberano"
                        },
                        new
                        {
                            CurrencySym = "VND",
                            CurrencyFullName = "Vietnamese Dong"
                        },
                        new
                        {
                            CurrencySym = "VUV",
                            CurrencyFullName = "Vanuatu Vatu"
                        },
                        new
                        {
                            CurrencySym = "WST",
                            CurrencyFullName = "Samoan Tala"
                        },
                        new
                        {
                            CurrencySym = "XAF",
                            CurrencyFullName = "CFA Franc BEAC"
                        },
                        new
                        {
                            CurrencySym = "XAG",
                            CurrencyFullName = "Silver Ounce"
                        },
                        new
                        {
                            CurrencySym = "XAU",
                            CurrencyFullName = "Gold Ounce"
                        },
                        new
                        {
                            CurrencySym = "XCD",
                            CurrencyFullName = "East Caribbean Dollar"
                        },
                        new
                        {
                            CurrencySym = "XDR",
                            CurrencyFullName = "Special Drawing Rights"
                        },
                        new
                        {
                            CurrencySym = "XOF",
                            CurrencyFullName = "CFA Franc BCEAO"
                        },
                        new
                        {
                            CurrencySym = "XPD",
                            CurrencyFullName = "Palladium Ounce"
                        },
                        new
                        {
                            CurrencySym = "XPF",
                            CurrencyFullName = "CFP Franc"
                        },
                        new
                        {
                            CurrencySym = "XPT",
                            CurrencyFullName = "Platinum Ounce"
                        },
                        new
                        {
                            CurrencySym = "YER",
                            CurrencyFullName = "Yemeni Rial"
                        },
                        new
                        {
                            CurrencySym = "ZAR",
                            CurrencyFullName = "South African Rand"
                        },
                        new
                        {
                            CurrencySym = "ZMW",
                            CurrencyFullName = "Zambian Kwacha"
                        },
                        new
                        {
                            CurrencySym = "ZWL",
                            CurrencyFullName = "Zimbabwean Dollar"
                        });
                });

            modelBuilder.Entity("MoneyMaker.Models.Portfolio", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("EntryCurrencySym")
                        .HasColumnType("TEXT");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId", "EntryCurrencySym", "Value");

                    b.ToTable("Portfolio");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
